name = "habit-formatting"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "plan-grind-db"
database_id = "bc3eab10-4fa9-4be1-849f-5c7cd2772c85"
